apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  # echo -n 'rootStrongPass' | base64
  MYSQL_ROOT_PASSWORD: cm9vdFN0cm9uZ1Bhc3M=
  # echo -n 'mudarDepois' | base64  (mesmo do script)
  MYSQL_APP_PASSWORD: bXVkYXJEZXBvaXM=
