name: CI/CD - K8s Projeto1 App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  # Testa build local (sem push) - garante que Dockerfiles estão corretos
  test-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Test build Backend
        run: docker build ./backend --file ./backend/Dockerfile --tag backend-test

      - name: Test build Frontend
        run: docker build ./frontend --file ./frontend/Dockerfile --tag frontend-test

  # Build do Backend e push para Docker Hub
  build-backend:
    runs-on: ubuntu-latest
    needs: test-build   # só roda se o test-build passar
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Docker Hub Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build & Push Backend
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USER }}/backend-k8s:latest
            ${{ secrets.DOCKER_HUB_USER }}/backend-k8s:${{ github.sha }}

  # Build do Frontend e push para Docker Hub
  build-frontend:
    runs-on: ubuntu-latest
    needs: test-build   # só roda se o test-build passar
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Docker Hub Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build & Push Frontend
        uses: docker/build-push-action@v4
        with:
          context: ./frontend
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USER }}/frontend-k8s:latest
            ${{ secrets.DOCKER_HUB_USER }}/frontend-k8s:${{ github.sha }}
